### ISSUE TITLE
List of shop items

### ISSUE THREAD

**Issue by DMarshallDeveloper** [DMarshallDeveloper/COMP313Micebreaker#12]
In order to start working on the shop and inventory parts of the program, I need to know what is actually going to be in the shop, and need the assets to put in place on screen @michelleanpre

**Comment by michelleanpre** [comment]
Hi Daniel,

There are 8 shop categories and 4 items in each. So 32 items in total and
I'll be able to get them to you by tuesday!

The category list is on the design brainstorm doc on drive. For now you can
potentially use substitute items, I will find some online and put it in the
drive folder c:

**Comment by DMarshallDeveloper** [comment]
This issue has been solved via the release of the numerical model
